{
 "title": "MING Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Interval", "query": "30s,1m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "EMQX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(emqx_connections_count{instance=\"emqx:18083\", job=\"emqx_stats\"})"
      }
     ]
    },
    {
     "title": "Active Topics",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(emqx_topics_count{instance=\"emqx:18083\", job=\"emqx_stats\"})",
       "legendFormat": "Active Topics"
      }
     ]
    },
    {
     "title": "Active Subscriptions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(emqx_suboptions_count{instance=\"emqx:18083\", job=\"emqx_stats\"})"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(emqx_connections_count{instance=\"emqx:18083\", job=\"emqx_stats\"})",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "Topics",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "emqx_topics_count{instance=\"emqx:18083\", job=\"emqx_stats\"}",
       "legendFormat": "Topics"
      }
     ]
    },
    {
     "title": "Subscriptions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "sum(emqx_suboptions_count{instance=\"emqx:18083\", job=\"emqx_stats\"})",
       "legendFormat": "Subscriptions"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(emqx_messages_received{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]) or irate(emqx_messages_received{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]))",
       "legendFormat": "Messages Received"
      },
      {
       "expr": "sum(rate(emqx_messages_sent{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]) or irate(emqx_messages_sent{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]))",
       "legendFormat": "Messages Sent"
      },
      {
       "expr": "sum(rate(emqx_messages_dropped{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]) or irate(emqx_messages_dropped{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]))",
       "legendFormat": "Messages Dropped"
      }
     ]
    },
    {
     "title": "Messages Sent Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(emqx_messages_sent{instance=\"emqx:18083\", job=\"emqx_stats\"})"
      }
     ]
    },
    {
     "title": "Messages Received Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(emqx_messages_received{instance=\"emqx:18083\", job=\"emqx_stats\"})"
      }
     ]
    },
    {
     "title": "Traffic Statistics",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(emqx_bytes_received{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]) or irate(emqx_bytes_received{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]))",
       "legendFormat": "Bytes received"
      },
      {
       "expr": "sum(rate(emqx_bytes_sent{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]) or irate(emqx_bytes_sent{instance=\"emqx:18083\", job=\"emqx_stats\"}[20s]))",
       "legendFormat": "Bytes sent"
      }
     ]
    },
    {
     "title": "Retained Messages",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(emqx_retained_count{instance=\"emqx:18083\", job=\"emqx_stats\"})"
      }
     ]
    },
    {
     "title": "Messages Dropped Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(emqx_messages_dropped{instance=\"emqx:18083\", job=\"emqx_stats\"})"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "emqx_connections_count{instance=\"emqx:18083\"}",
       "legendFormat": "Current"
      }
     ]
    }
   ]
  },
  {
   "title": "Influxdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_users_total{instance=\"influxdb:8086\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tokens total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "influxdb_tokens_total{instance=\"influxdb:8086\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus http request to influxdb",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 2 },
     "targets": [
      {
       "expr": "http_api_requests_total{handler=\"platform\", instance=\"influxdb:8086\", job=\"influxdb\", method=\"GET\", path=\"/metrics\", response_code=\"200\", status=\"2XX\", user_agent=\"Prometheus\"}",
       "legendFormat": "{{user_agent}}"
      }
     ]
    }
   ]
  },
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Dashboard count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafana_stat_totals_dashboard" }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafana_stat_total_users" }
   ]
  },
  {
   "title": "Grafana performance",
   "type": "graph",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\".*grafana\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafana\"})",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Postgres (postgres exporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "graph",
     "description": "1 Minute rate of transactions committed or rollback.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum ((rate(pg_stat_database_xact_commit[$Interval])))",
       "legendFormat": "committed"
      },
      {
       "expr": "sum ((rate(pg_stat_database_xact_rollback[$Interval])))",
       "legendFormat": "rollback"
      }
     ]
    },
    {
     "title": "Active clients",
     "type": "stat",
     "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"active\", instance=\"postgres-exporter:9187\"})"
      }
     ]
    },
    {
     "title": "Connections by database (stacked)",
     "type": "graph",
     "description": "View: pg_stat_activity",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(datname) (pg_stat_activity_count{instance=\"postgres-exporter:9187\"})",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host (node exporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy (bym)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A / $B * 100", "type": "math" }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\".*\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 4, "w": 4, "x": 2, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"node_exporter:9100\",job=\"node_exporter\"} - node_boot_time_seconds{instance=\"node_exporter:9100\",job=\"node_exporter\"}"
      }
     ]
    }
   ]
  }
 ]
}